// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AuthPayload struct {
	Success bool          `json:"success"`
	Message string        `json:"message"`
	Data    *AuthResponse `json:"data,omitempty"`
}

type AuthResponse struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type BusinessHours struct {
	OpenTime  string   `json:"openTime"`
	CloseTime string   `json:"closeTime"`
	Days      []string `json:"days"`
}

type BusinessHoursInput struct {
	OpenTime  string   `json:"openTime"`
	CloseTime string   `json:"closeTime"`
	Days      []string `json:"days"`
}

type Comment struct {
	ID        string     `json:"id"`
	Text      string     `json:"text"`
	Author    *User      `json:"author"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type ContactDetails struct {
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
}

type ContactDetailsInput struct {
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	Address string `json:"address"`
}

type Coordinates struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type CoordinatesInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type CreateItemInput struct {
	Name        string         `json:"name"`
	Price       float64        `json:"price"`
	Description string         `json:"description"`
	Category    string         `json:"category"`
	SubCategory *string        `json:"subCategory,omitempty"`
	Stock       int            `json:"stock"`
	CoverPhoto  string         `json:"coverPhoto"`
	OtherPhotos []string       `json:"otherPhotos"`
	Sku         *string        `json:"sku,omitempty"`
	Barcode     *string        `json:"barcode,omitempty"`
	Weight      *float64       `json:"weight,omitempty"`
	Unit        *string        `json:"unit,omitempty"`
	ExpiryDate  *time.Time     `json:"expiryDate,omitempty"`
	Supplier    *string        `json:"supplier,omitempty"`
	Brand       *string        `json:"brand,omitempty"`
	Origin      *string        `json:"origin,omitempty"`
	Tags        []string       `json:"tags"`
	ShopID      string         `json:"shopId"`
	Discount    *DiscountInput `json:"discount,omitempty"`
}

type CreatePostInput struct {
	Title    string         `json:"title"`
	Text     string         `json:"text"`
	Photos   []string       `json:"photos,omitempty"`
	Types    []string       `json:"types,omitempty"`
	Location *LocationInput `json:"location,omitempty"`
}

type CreateShopInput struct {
	Name           string                `json:"name"`
	Location       string                `json:"location"`
	Coordinates    *CoordinatesInput     `json:"coordinates"`
	CoverPhoto     string                `json:"coverPhoto"`
	OtherPhotos    []string              `json:"otherPhotos"`
	BusinessHours  *BusinessHoursInput   `json:"businessHours"`
	BusinessType   BusinessType          `json:"businessType"`
	PaymentMethods *PaymentMethodsInput  `json:"paymentMethods"`
	Delivery       *DeliveryOptionsInput `json:"delivery"`
	SocialMedia    *SocialMediaInput     `json:"socialMedia"`
	ContactDetails *ContactDetailsInput  `json:"contactDetails"`
}

type CreateUserInput struct {
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Email     string   `json:"email"`
	Password  string   `json:"password"`
	Role      UserRole `json:"role"`
}

type DeletePayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type DeliveryOptions struct {
	Available bool     `json:"available"`
	Radius    *float64 `json:"radius,omitempty"`
	Fee       *float64 `json:"fee,omitempty"`
	MinOrder  *float64 `json:"minOrder,omitempty"`
}

type DeliveryOptionsInput struct {
	Available bool     `json:"available"`
	Radius    *float64 `json:"radius,omitempty"`
	Fee       *float64 `json:"fee,omitempty"`
	MinOrder  *float64 `json:"minOrder,omitempty"`
}

type Discount struct {
	Percentage *float64   `json:"percentage,omitempty"`
	ValidUntil *time.Time `json:"validUntil,omitempty"`
}

type DiscountInput struct {
	Percentage *float64   `json:"percentage,omitempty"`
	ValidUntil *time.Time `json:"validUntil,omitempty"`
}

type GoogleLoginInput struct {
	Credential string    `json:"credential"`
	Role       *UserRole `json:"role,omitempty"`
}

type Item struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Price       float64    `json:"price"`
	Description string     `json:"description"`
	Category    string     `json:"category"`
	SubCategory *string    `json:"subCategory,omitempty"`
	Stock       int        `json:"stock"`
	CoverPhoto  string     `json:"coverPhoto"`
	OtherPhotos []string   `json:"otherPhotos"`
	Sku         *string    `json:"sku,omitempty"`
	Barcode     *string    `json:"barcode,omitempty"`
	Weight      *float64   `json:"weight,omitempty"`
	Unit        *string    `json:"unit,omitempty"`
	ExpiryDate  *time.Time `json:"expiryDate,omitempty"`
	Supplier    *string    `json:"supplier,omitempty"`
	Brand       *string    `json:"brand,omitempty"`
	Origin      *string    `json:"origin,omitempty"`
	Tags        []string   `json:"tags"`
	IsActive    bool       `json:"isActive"`
	Discount    *Discount  `json:"discount,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	ShopID      string     `json:"shopId"`
}

type ItemPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *Item  `json:"data,omitempty"`
}

type ItemsPayload struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Data    []*Item `json:"data"`
}

type Location struct {
	Lat  float64 `json:"lat"`
	Lng  float64 `json:"lng"`
	Name string  `json:"name"`
}

type LocationInput struct {
	Lat  float64 `json:"lat"`
	Lng  float64 `json:"lng"`
	Name string  `json:"name"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PaymentMethods struct {
	Cash    bool `json:"cash"`
	Gcash   bool `json:"gcash"`
	Paymaya bool `json:"paymaya"`
	Card    bool `json:"card"`
}

type PaymentMethodsInput struct {
	Cash    bool `json:"cash"`
	Gcash   bool `json:"gcash"`
	Paymaya bool `json:"paymaya"`
	Card    bool `json:"card"`
}

type Post struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Text         string     `json:"text"`
	Photos       []string   `json:"photos"`
	Types        []string   `json:"types"`
	Author       *User      `json:"author"`
	Location     *Location  `json:"location,omitempty"`
	Likes        int        `json:"likes"`
	IsLiked      bool       `json:"isLiked"`
	Comments     []*Comment `json:"comments"`
	CommentCount int        `json:"commentCount"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

type PostPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *Post  `json:"data,omitempty"`
}

type PostsPayload struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Data    []*Post `json:"data"`
	Total   int     `json:"total"`
	Page    int     `json:"page"`
	Limit   int     `json:"limit"`
}

type ProductSearchInput struct {
	Query    *string  `json:"query,omitempty"`
	Category *string  `json:"category,omitempty"`
	MinPrice *float64 `json:"minPrice,omitempty"`
	MaxPrice *float64 `json:"maxPrice,omitempty"`
	ShopID   *string  `json:"shopId,omitempty"`
	IsActive *bool    `json:"isActive,omitempty"`
	Page     *int     `json:"page,omitempty"`
	Limit    *int     `json:"limit,omitempty"`
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type Shop struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	Location       string           `json:"location"`
	Coordinates    *Coordinates     `json:"coordinates"`
	CoverPhoto     string           `json:"coverPhoto"`
	OtherPhotos    []string         `json:"otherPhotos"`
	BusinessHours  *BusinessHours   `json:"businessHours"`
	BusinessType   BusinessType     `json:"businessType"`
	PaymentMethods *PaymentMethods  `json:"paymentMethods"`
	Delivery       *DeliveryOptions `json:"delivery"`
	SocialMedia    *SocialMedia     `json:"socialMedia"`
	Verification   *Verification    `json:"verification"`
	ContactDetails *ContactDetails  `json:"contactDetails"`
	Inventory      []*Item          `json:"inventory"`
	CreatedAt      time.Time        `json:"createdAt"`
	UpdatedAt      *time.Time       `json:"updatedAt,omitempty"`
	CreatedBy      string           `json:"createdBy"`
	Status         ShopStatus       `json:"status"`
}

type ShopPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *Shop  `json:"data,omitempty"`
}

type ShopSearchInput struct {
	Query        *string       `json:"query,omitempty"`
	Lat          *float64      `json:"lat,omitempty"`
	Lng          *float64      `json:"lng,omitempty"`
	Radius       *float64      `json:"radius,omitempty"`
	Category     *string       `json:"category,omitempty"`
	BusinessType *BusinessType `json:"businessType,omitempty"`
	Status       *ShopStatus   `json:"status,omitempty"`
	Page         *int          `json:"page,omitempty"`
	Limit        *int          `json:"limit,omitempty"`
}

type ShopsPayload struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Data    []*Shop `json:"data"`
}

type SignupInput struct {
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      *UserRole `json:"role,omitempty"`
}

type SocialMedia struct {
	Facebook  *string `json:"facebook,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
}

type SocialMediaInput struct {
	Facebook  *string `json:"facebook,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
}

type Subscription struct {
}

type UpdateItemInput struct {
	Name        *string        `json:"name,omitempty"`
	Price       *float64       `json:"price,omitempty"`
	Description *string        `json:"description,omitempty"`
	Category    *string        `json:"category,omitempty"`
	SubCategory *string        `json:"subCategory,omitempty"`
	Stock       *int           `json:"stock,omitempty"`
	CoverPhoto  *string        `json:"coverPhoto,omitempty"`
	OtherPhotos []string       `json:"otherPhotos,omitempty"`
	Sku         *string        `json:"sku,omitempty"`
	Barcode     *string        `json:"barcode,omitempty"`
	Weight      *float64       `json:"weight,omitempty"`
	Unit        *string        `json:"unit,omitempty"`
	ExpiryDate  *time.Time     `json:"expiryDate,omitempty"`
	Supplier    *string        `json:"supplier,omitempty"`
	Brand       *string        `json:"brand,omitempty"`
	Origin      *string        `json:"origin,omitempty"`
	Tags        []string       `json:"tags,omitempty"`
	Discount    *DiscountInput `json:"discount,omitempty"`
}

type UpdatePostInput struct {
	Title    *string        `json:"title,omitempty"`
	Text     *string        `json:"text,omitempty"`
	Photos   []string       `json:"photos,omitempty"`
	Types    []string       `json:"types,omitempty"`
	Location *LocationInput `json:"location,omitempty"`
}

type UpdateProfileInput struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type UpdateShopInput struct {
	Name           *string               `json:"name,omitempty"`
	Location       *string               `json:"location,omitempty"`
	Coordinates    *CoordinatesInput     `json:"coordinates,omitempty"`
	CoverPhoto     *string               `json:"coverPhoto,omitempty"`
	OtherPhotos    []string              `json:"otherPhotos,omitempty"`
	BusinessHours  *BusinessHoursInput   `json:"businessHours,omitempty"`
	BusinessType   *BusinessType         `json:"businessType,omitempty"`
	PaymentMethods *PaymentMethodsInput  `json:"paymentMethods,omitempty"`
	Delivery       *DeliveryOptionsInput `json:"delivery,omitempty"`
	SocialMedia    *SocialMediaInput     `json:"socialMedia,omitempty"`
	ContactDetails *ContactDetailsInput  `json:"contactDetails,omitempty"`
	Status         *ShopStatus           `json:"status,omitempty"`
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Phone     *string    `json:"phone,omitempty"`
	Role      UserRole   `json:"role"`
	Shops     []string   `json:"shops,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	IsActive  bool       `json:"isActive"`
}

type UserPayload struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    *User  `json:"data,omitempty"`
}

type Verification struct {
	IsVerified     bool       `json:"isVerified"`
	VerifiedDate   *time.Time `json:"verifiedDate,omitempty"`
	VerificationID *string    `json:"verificationId,omitempty"`
}

type BusinessType string

const (
	BusinessTypeSariSariStore    BusinessType = "SARI_SARI_STORE"
	BusinessTypeGrocery          BusinessType = "GROCERY"
	BusinessTypeConvenienceStore BusinessType = "CONVENIENCE_STORE"
	BusinessTypeMiniMart         BusinessType = "MINI_MART"
)

var AllBusinessType = []BusinessType{
	BusinessTypeSariSariStore,
	BusinessTypeGrocery,
	BusinessTypeConvenienceStore,
	BusinessTypeMiniMart,
}

func (e BusinessType) IsValid() bool {
	switch e {
	case BusinessTypeSariSariStore, BusinessTypeGrocery, BusinessTypeConvenienceStore, BusinessTypeMiniMart:
		return true
	}
	return false
}

func (e BusinessType) String() string {
	return string(e)
}

func (e *BusinessType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BusinessType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BusinessType", str)
	}
	return nil
}

func (e BusinessType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BusinessType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BusinessType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ItemStatus string

const (
	ItemStatusActive   ItemStatus = "ACTIVE"
	ItemStatusInactive ItemStatus = "INACTIVE"
)

var AllItemStatus = []ItemStatus{
	ItemStatusActive,
	ItemStatusInactive,
}

func (e ItemStatus) IsValid() bool {
	switch e {
	case ItemStatusActive, ItemStatusInactive:
		return true
	}
	return false
}

func (e ItemStatus) String() string {
	return string(e)
}

func (e *ItemStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ItemStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ItemStatus", str)
	}
	return nil
}

func (e ItemStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ItemStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ItemStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ShopStatus string

const (
	ShopStatusActive    ShopStatus = "ACTIVE"
	ShopStatusInactive  ShopStatus = "INACTIVE"
	ShopStatusSuspended ShopStatus = "SUSPENDED"
)

var AllShopStatus = []ShopStatus{
	ShopStatusActive,
	ShopStatusInactive,
	ShopStatusSuspended,
}

func (e ShopStatus) IsValid() bool {
	switch e {
	case ShopStatusActive, ShopStatusInactive, ShopStatusSuspended:
		return true
	}
	return false
}

func (e ShopStatus) String() string {
	return string(e)
}

func (e *ShopStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShopStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShopStatus", str)
	}
	return nil
}

func (e ShopStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShopStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShopStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "CUSTOMER"
	UserRoleOwner    UserRole = "OWNER"
	UserRoleAdmin    UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleCustomer,
	UserRoleOwner,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleCustomer, UserRoleOwner, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
